export const predefinedServices = [
  "Accounts Outsourcing Services",
  "Payroll Management Services",
  "Compilation of Final Accounts",
  "Preparation of Financial Statements",
  "All Statutory Compliance Services",
  "Statutory Audit Services",
  "Internal Audit/ Concurrent Audit Services",
  "Certification and Attest functions",
  "Special Audit Services",
  "Investigation Audit",
  "Fixed Assets Audit",
  "Stock Audit",
  "Income Tax Audit services",
  "Income Tax planning and Consultancy services",
  "GST Audit & Consultancy services",
  "Withholding Taxation as per clauses of DTAA with various countries",
  "Transfer Pricing Studies & Certification services",
  "Tax Representations services",
  "Appeals before Appellate Authorities",
  "GHMC- Service tax case handled and appeared before Appellate Tribunal",
  "Company Formation services",
  "IPO advisory services",
  "Mergers & Acquisition services",
  "Company Support services",
  "Stock Management Services",
  "Fixed Asset Management Services",
  "Sales Accounts management",
  "MIS report Services",
  "Budget Forecasting Services",
  "Financial management planning and financial policy determination",
  "Costing and Accounting System Design and Review",
  "Advising management on principles of organization and methods for effective delegation and planning of work",
  "Appraisal of personnel policies and practices",
  "Business Policy, corporate planning, organization development, growth and diversification",
  "Corporate Training",
  "Registration with various Statutory and Revenue Authorities",
  "Company, LLP, Partnership firm, Societies and Trust formation services",
  "Preparation of various Agreements and MOU’s",
];
